// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juxgfatikkphmuxlmduo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1eGdmYXRpa2twaG11eGxtZHVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjQ1MzQsImV4cCI6MjA2MzQwMDUzNH0.lh4PfGfH0O-ubAt1GlhNbSklLrlVF2WAunAGMUHINgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);